extern void game_background();
extern void set_chess_pieces(int pixel_x, int pixel_y, int colour);
extern void show_winner(int winner);
extern void regret_imageshow(int x, int y);
extern void get_username(char* userblack, char* userwhite);
extern int get_mouse(int *px, int*py);
extern void change_x_px(int *x, int *y, int* px, int*py);
extern void get_timeshow(int* time);
extern void game_begin();
void get_pattern(int* pvp);